{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Simple Twitter",
    "description": "This is a sample server Simple Twitter server."
  },
  "host": "localhost:3000",
  "basePath": "",
  "tags": [],
  "schemes": [
    "https",
    "http"
  ],
  "security": [
    {
      "JWT": []
    }
  ],
  "securityDefinitions": {
    "JWT": {
      "description": "bearer + token",
      "type": "apiKey",
      "in": "header",
      "name": "Authorization"
    }
  },
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/users/signin": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "sign in account",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "properties": {
                "email": {
                  "type": "string",
                  "example": "root@example.com"
                },
                "password": {
                  "type": "string",
                  "example": "12345678"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "status": {
                  "example": "success"
                },
                "message": {
                  "example": "ok"
                },
                "token": {
                  "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjE1NTI0NjQ3fQ.uMGmztQxQWvZ1fES3_UOVSZmzJ3SVrnOUZmxGoGJA7Y"
                },
                "user": {
                  "$ref": "#/definitions/User"
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "密碼錯誤/使用者未註冊"
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "伺服器錯誤請稍後"
                }
              }
            }
          }
        }
      }
    },
    "/api/users": {
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "sign up account",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "properties": {
                "account": {
                  "type": "string",
                  "example": "user"
                },
                "name": {
                  "type": "string",
                  "example": "Jason"
                },
                "email": {
                  "type": "string",
                  "example": "test@example.com"
                },
                "password": {
                  "type": "string",
                  "example": "12345678"
                },
                "checkPassword": {
                  "type": "string",
                  "example": "12345678"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "status": {
                  "example": "success"
                },
                "message": {
                  "example": "註冊成功"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": [
                    "帳號已重複",
                    "信箱已重複"
                  ]
                },
                "userData": {
                  "example": {
                    "account": "user",
                    "name": "Jason",
                    "email": "test@example.com",
                    "password": "12345678",
                    "checkPassword": "12345678"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "註冊流程-伺服器錯誤請稍後"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/top": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get top 10 users",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get specific user",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 1,
                "account": "Jhon Doe",
                "name": "Jhon Doe",
                "email": "user1@example.com",
                "password": "$2a$10$xetmBvyqkCa21C0PQgxAF.zuav.3Xw8oZFqEZ3RPQu/SLhlzz685i",
                "role": "測試",
                "avatar": "https://loremflickr.com/320/240/dog/?lock=43.2526391118924",
                "introduction": "Poskiajfas slkda",
                "cover": "https://loremflickr.com/320/240/landscape/?lock=11.963473892940701",
                "isAdmin": false,
                "createdAt": "2021-03-10T05:12:05.000Z",
                "updatedAt": "2021-03-10T17:12:48.000Z",
                "FollowingsCount": 3,
                "FollowersCount": 5,
                "userTweetsCount": 3,
                "likedTweetsCount": 4,
                "replyTweetsCount": 5
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "個人資料-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "edit specific user",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "string",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "type": "string",
            "required": true,
            "schema": {
              "properties": {
                "name": {
                  "type": "string",
                  "example": "Jhon Doe"
                },
                "introduction": {
                  "type": "string",
                  "example": "Hi"
                },
                "cover": {
                  "type": "string",
                  "example": "https: //i.imgur.com/l0Jc1MO.jp"
                },
                "avatar": {
                  "type": "string",
                  "example": "https: //i.imgur.com/l0Jc1MO.jp"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "status": {
                  "example": "success"
                },
                "message": {
                  "example": "修改成功"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": [
                    "請輸入名稱"
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "編輯個人資料-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}/account": {
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "edit user account data",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "string",
            "required": true,
            "type": "string"
          },
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "properties": {
                "account": {
                  "type": "string",
                  "example": "user"
                },
                "name": {
                  "type": "string",
                  "example": "Jason"
                },
                "email": {
                  "type": "string",
                  "example": "test@example.com"
                },
                "password": {
                  "type": "string",
                  "example": "12345678"
                },
                "checkPassword": {
                  "type": "string",
                  "example": "12345678"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "properties": {
                "status": {
                  "example": "success"
                },
                "message": {
                  "example": "修改成功"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": [
                    "請輸入名稱"
                  ]
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "編輯個人資料-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}/followings": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get user following list",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 6,
                "name": "Don Ebert",
                "account": "user6",
                "email": "user6@example.com",
                "avatar": "https://loremflickr.com/320/240/dog/?lock=25.64053667078563",
                "introduction": "Incidunt rerum sed explicabo. Aliquam illo ex quos sint. Occaecati mollitia facilis in voluptatem rem. Est eligendi recusandae itaque omnis voluptatum qui. Doloremque consequatur deserunt officiis qui et rerum. In quidem a voluptate corrupti.",
                "followingId": 6,
                "followerId": 5,
                "isFollowed": false
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "getfollowings-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}/followers": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get user follower list",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 6,
                "name": "Don Ebert",
                "account": "user6",
                "email": "user6@example.com",
                "avatar": "https://loremflickr.com/320/240/dog/?lock=25.64053667078563",
                "introduction": "Incidunt rerum sed explicabo. Aliquam illo ex quos sint. Occaecati mollitia facilis in voluptatem rem. Est eligendi recusandae itaque omnis voluptatum qui. Doloremque consequatur deserunt officiis qui et rerum. In quidem a voluptate corrupti.",
                "followingId": 6,
                "followerId": 5,
                "isFollowed": false
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "getfollowings-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}/replied_tweets": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get user reply tweets",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 24,
                "UserId": 7,
                "TweetId": 28,
                "comment": "Tempora suscipit reiciendis autem cum odit optio.",
                "createdAt": "2021-03-10T05:12:06.000Z",
                "updatedAt": "2021-03-10T05:12:06.000Z",
                "likeCount": 1,
                "replyCount": 2,
                "Tweet": {
                  "id": 28,
                  "UserId": 2,
                  "description": "qui id doloremque",
                  "createdAt": "2021-03-10T05:12:06.000Z",
                  "updatedAt": "2021-03-10T05:12:06.000Z",
                  "Likes": {
                    "id": 1,
                    "UserId": 7,
                    "TweetId": 28,
                    "createdAt": "2021-03-10T05:12:06.000Z",
                    "updatedAt": "2021-03-10T05:12:06.000Z"
                  }
                },
                "User": {
                  "id": 7,
                  "name": "Tyler Rath",
                  "account": "user7",
                  "email": "user7@example.com",
                  "avatar": "https://loremflickr.com/320/240/dog/?lock=29.475156019746052",
                  "isAdmin": 0
                },
                "isLiked": false
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "getReplied_tweets-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}/likes": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get user like list",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 28,
                "UserId": 2,
                "description": "qui id doloremque",
                "createdAt": "2021-03-10T05:12:06.000Z",
                "updatedAt": "2021-03-10T05:12:06.000Z",
                "likeCount": 1,
                "replyCount": 2,
                "Likes": {
                  "id": 1,
                  "UserId": 7,
                  "TweetId": 28,
                  "createdAt": "2021-03-10T05:12:06.000Z",
                  "updatedAt": "2021-03-10T05:12:06.000Z"
                },
                "User": {
                  "id": 2,
                  "name": "Ms. Evan Nikolaus",
                  "account": "user2",
                  "email": "user2@example.com",
                  "avatar": "https://loremflickr.com/320/240/dog/?lock=17.912548616863223",
                  "isAdmin": 0
                },
                "isLiked": false
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "getUserLikes-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/{id}/tweets": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "get user tweets list",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 22,
                "UserId": 7,
                "description": "asperiores labore similique",
                "createdAt": "2021-03-10T05:12:06.000Z",
                "updatedAt": "2021-03-10T05:12:06.000Z",
                "likeCount": 0,
                "replyCount": 2,
                "Likes": {
                  "id": 1,
                  "UserId": 1,
                  "TweetId": 15,
                  "createdAt": "2021-03-10T05:12:06.000Z",
                  "updatedAt": "2021-03-10T05:12:06.000Z"
                },
                "User": {
                  "id": 7,
                  "name": "Tyler Rath",
                  "account": "user7",
                  "email": "user7@example.com",
                  "avatar": "https://loremflickr.com/320/240/dog/?lock=29.475156019746052",
                  "isAdmin": 0
                },
                "Time": "2 days",
                "isLiked": false
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "getUserTweets-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/tweets/{id}": {
      "get": {
        "tags": [
          "Tweets"
        ],
        "summary": "get specific tweet",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "id": 1,
                "UserId": 6,
                "description": "nulla et dicta",
                "createdAt": "2021-03-10T05:12:06.000Z",
                "likeCount": 0,
                "replyCount": 1,
                "Likes": [],
                "User": {
                  "id": 6,
                  "name": "Don Ebert",
                  "account": "user6",
                  "email": "user6@example.com",
                  "avatar": "https://loremflickr.com/320/240/dog/?lock=25.64053667078563",
                  "isAdmin": false
                },
                "isLiked": false
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "瀏覽單一推文-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": [
          "Tweets"
        ],
        "summary": "edit specific tweet",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "string",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "type": "string",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Tweet",
              "properties": {
                "description": {
                  "type": "text",
                  "example": "hahahaha"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "status": "success",
                "message": "category was successfully to update",
                "data": {
                  "id": 1,
                  "UserId": 1,
                  "description": "sfdauijnoge skojdasd"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "修改推特-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": [
          "Tweets"
        ],
        "summary": "delete specific tweet",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "status": "success",
                "message": "category was successfully to delete"
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "刪除推特-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/tweets/{id}/like": {
      "post": {
        "tags": [
          "Tweets"
        ],
        "summary": "like specific tweet",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "status": "success",
                "message": "like was successfully create"
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "推特點讚-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/tweets/{id}/unlike": {
      "post": {
        "tags": [
          "Tweets"
        ],
        "summary": "unlike specific tweet",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "example": {
                "status": "success",
                "message": "like was successfully deleted"
              }
            }
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error",
            "schema": {
              "properties": {
                "status": {
                  "example": "error"
                },
                "message": {
                  "example": "移除點讚-伺服器錯誤請稍後"
                },
                "err": {
                  "example": "err message"
                }
              }
            }
          }
        }
      }
    },
    "/api/tweets/{tweet_id}/replies": {
      "post": {
        "tags": [
          "Tweets"
        ],
        "summary": "add reply to specific tweet",
        "parameters": [
          {
            "name": "tweet_id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "type": "string",
            "required": true,
            "schema": {
              "properties": {
                "comment": {
                  "type": "text",
                  "example": "hahahaha"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      },
      "get": {
        "tags": [
          "Tweets"
        ],
        "summary": "get all replies of specific tweet",
        "parameters": [
          {
            "name": "tweet_id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/tweets": {
      "post": {
        "tags": [
          "Tweets"
        ],
        "summary": "post new tweet",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "get": {
        "tags": [
          "Tweets"
        ],
        "summary": "get all tweets",
        "responses": {}
      }
    },
    "/api/replies/{id}": {
      "delete": {
        "tags": [
          "replies"
        ],
        "summary": "delete specific reply",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      },
      "put": {
        "tags": [
          "replies"
        ],
        "summary": "edit specific reply",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "type": "string",
            "required": true,
            "schema": {
              "properties": {
                "comment": {
                  "type": "text",
                  "example": "hahahaha"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/followships/{followingId}": {
      "delete": {
        "tags": [
          "followship"
        ],
        "summary": "delete specific followship",
        "parameters": [
          {
            "name": "followingId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        },
        "security": [
          {
            "JWT": []
          }
        ]
      }
    },
    "/api/followships": {
      "post": {
        "tags": [
          "followship"
        ],
        "summary": "add specific followship",
        "parameters": [
          {
            "in": "body",
            "name": "body",
            "required": true,
            "schema": {
              "properties": {
                "id": {
                  "type": "integer",
                  "example": "1"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    },
    "/api/admin/users": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "get all users",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/admin/tweets": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "get all tweets",
        "parameters": [],
        "responses": {
          "200": {
            "description": "OK"
          },
          "400": {
            "description": "Bad Request"
          },
          "500": {
            "description": "Internal Server Error"
          }
        }
      }
    },
    "/api/admin/tweets/{id}": {
      "delete": {
        "tags": [
          "Admin"
        ],
        "summary": "admin delete specific tweet",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {}
      }
    }
  },
  "definitions": {
    "User": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "account": {
          "type": "string",
          "example": "Jhon Doe"
        },
        "name": {
          "type": "string",
          "example": "Jhon Doe"
        },
        "email": {
          "type": "string",
          "example": "root@example.com"
        },
        "password": {
          "type": "string",
          "example": "12345678"
        },
        "role": {
          "type": "string",
          "example": "admin"
        },
        "avatar": {
          "type": "string",
          "example": "https: //i.imgur.com/l0Jc1MO.jp"
        },
        "introduction": {
          "type": "string",
          "example": "Hi"
        }
      },
      "required": [
        "name",
        "email",
        "password"
      ]
    },
    "Tweet": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "UserId": {
          "type": "integer"
        },
        "description": {
          "type": "text",
          "example": "sfdauijnoge skojdasd"
        }
      },
      "required": [
        "type",
        "description"
      ]
    },
    "Like": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "UserId": {
          "type": "integer"
        },
        "TweetId": {
          "type": "integer"
        }
      },
      "required": []
    },
    "Reply": {
      "type": "object",
      "properties": {
        "id": {
          "type": "integer"
        },
        "UserId": {
          "type": "integer"
        },
        "TweetId": {
          "type": "integer"
        },
        " comment": {
          "type": "text"
        }
      },
      "required": []
    }
  }
}